export const GET_COLLECTION = 'GET_COLLECTION'
export const ADD_COLLECTION = 'ADD_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'

// ◆ 動作_對象 (動詞_名詞) ADD_TODO , DELETE_TODO , UPDATE_TODO
// ◆ 功能/區域_動作_對象 (名詞_動詞_名詞) CART_ADD_ITEM , CART_DELETE_ITEM , PRODUCT_ADD_ITEM
// ◆ 動作_名詞_狀態 (動詞_名詞_形容詞/動詞) FETCH_USER_REQUEST , FETCH_USER_SUCCESS , FETCH_USER_FAIL , FETCH_USER_COMPLETE
